version: '3.2'
services:
  web:
    image: ece4222020wt1/youcanbenefit-frontend
    environment:
      - API_SERVICE=api
      - API_PORT=3000
    ports:
      - 4200:80

  api:
    image: ece4222020wt1/youcanbenefit-backend
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - discovery.type=single-node
